#!/bin/bash

echo "==================================="
echo "GPU Monitor - 添加桌面小组件指南"
echo "==================================="
echo ""
echo "应用已在菜单栏运行！"
echo ""
echo "如何添加桌面小组件："
echo ""
echo "1. 右键点击桌面空白处"
echo "2. 选择 '编辑小组件' 或 'Edit Widgets'"
echo "3. 点击左上角的 '+' 按钮"
echo "4. 搜索 'GPU' 或 'GPUWidget'"
echo "5. 拖拽 'GPU 监控' 到桌面"
echo "6. 选择尺寸（推荐：中等或大型）"
echo "7. 点击 '完成'"
echo ""
echo "详细说明请查看: USAGE.md"
echo ""
echo "配置文件位置: ~/.config/gpu_monitor/config.json"
echo ""
